### ISSUE TITLE
Peer - Peer code review wk2

### ISSUE THREAD

**Issue by aceDavon** [aceDavon/Portfolio-project#5]
Morning session partners on Portfolio project

**Comment by altontonn** [comment]
Good job on the desktop and mobile version, I have no issue <br>
<img src="https://media0.giphy.com/media/xUOrwiqZxXUiJewDrq/giphy.gif"/>
Happy Coding

**Comment by muskan2532150** [comment]
You already used an h1 tag in the main container. You can only have one(1) h1 tag per page( used in contact container). This is for semantic reasons.

**Comment by aceDavon** [comment]
Thanks, guys for the suggestions, I fixed them already!
